"""ai kısımları için weekly plan ve yeni plan task eklendi 

Revision ID: 45da953b1e22
Revises: c5f247ad81d2
Create Date: 2025-08-01 19:53:18.474108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45da953b1e22'
down_revision: Union[str, Sequence[str], None] = 'c5f247ad81d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_plans', 'completion_ratio')
    op.drop_column('weekly_plans', 'allocated_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_plans', sa.Column('allocated_minutes', sa.INTEGER(), nullable=True))
    op.add_column('weekly_plans', sa.Column('completion_ratio', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
