"""reading_text_data is_resolved eklendi 

Revision ID: c5f247ad81d2
Revises: 452534a93b56
Create Date: 2025-07-29 21:55:20.251509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f247ad81d2'
down_revision: Union[str, Sequence[str], None] = '452534a93b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_text_data', sa.Column('is_resolved_data', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_text_data', 'is_resolved_data')
    # ### end Alembic commands ###
